apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-service
  template:
    metadata:
      labels:
        app: notes-service
    spec:
      containers:
        - name: notes-service
          image: notes-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"